VC3EYE/Pages/AddService.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using System.Security.Claims;

using VC3EYE.Data;
using VC3EYE.Entities;
using VC3EYE.Models;

namespace VC3EYE.Pages
{
    [Authorize(Roles = SiteRoles.Administrator + "," + SiteRoles.User)]
    public class AddServiceModel : PageModel
    {
        private readonly Vc3eyeContext _db;

        public string Message { get; set; }

        public AddServiceModel(Vc3eyeContext db)
        {
            _db = db;
        }

        [BindProperty]
        public ServiceModel currentService { get; set; }

        /// <summary>
        /// When page load
        /// </summary>
        public void OnGet()
        {
            //preload
            Message = "Please enter the service URL or IP for checking!";
        }

        /// <summary>
        /// Action when click ADD
        /// </summary>
        /// <returns></returns>
        public IActionResult OnPostAdd()
        {
            //process if input is valid
            if (ModelState.IsValid)
            {
                //check one of required fields in input and set feedback
                if (currentService.ServiceURL == null && currentService.IPAddress == null)
                {
                    Message = "Please enter the service URL or IP for checking!";

                    //pop up 2
                    string script = "<script>showMessage();</script>";
                    ViewData["Script"] = script;

                    return Page();
                }

                //declare
                var sc = new ServiceController(_db);
                currentService.UserID = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier).ToString());

                //flag
                bool confirmation = sc.AddService(currentService);

                var lm = new LogsManager(_db);
                var userLog = new Log()
                {
                    LogName = "Add",
                    LogDescription = "Service - " + currentService.ServiceName,
                    IsAudit = false,
                    DateAdded = DateTime.Now,
                    UserId = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier).ToString())
                };

                //logging
                lm.AddUserActivityLog(userLog);

                //message log
                Message = "Service added successful!";

                //go to Service List
                return RedirectToPage("ServicesList");
            }

            // Add logic
            return Page();
        }


        /// <summary>
        /// Action when hit RESET
        /// </summary>
        public IActionResult OnPostReset()
        {
            //call reset value function
            //InitPage();

            ModelState.Clear(); // clear any validation errors

            // Add logic
            return Page();
        }


        public IActionResult OnPostGoBack()
        {
            ModelState.Clear(); // clear any validation errors

            //reload page
            return RedirectToPage("ServicesList");
        }
    }
}

VC3EYE/Pages/Chartsofservices.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using VC3EYE.Data;
using VC3EYE.Entities;

namespace VC3EYE.Pages
{
    public class ChartsofservicesModel : PageModel
    {
        private Vc3eyeContext _db;
        public ChartsofservicesModel(Vc3eyeContext db)
        {
            _db = db;
        }
        [BindProperty]
       public List<ServiceDownHistory> serviceDownHistory { get; set; } = default!;

        public List<string> Months { get; set; }
        public List<int> Down { get; set; }
        public async Task OnGetAsync()
        {
            serviceDownHistory = await _db.ServiceDownHistories.ToListAsync();
            var downByMonth = serviceDownHistory.GroupBy(s => new { s.DateAdded.Year, s.DateAdded.Month, s.DateAdded.Day })
                                 .Select(g => new { Month = new DateTime(g.Key.Year, g.Key.Month, g.Key.Day),
                                  MGType = g.Count(a => a.ServiceId == 24) })
                                 .ToArray();
            // Create the X-axis labels 
            Months = downByMonth.Select(s => s.Month.ToString("yyyy-MMM-dd")).ToList();
            //Create Y-Axis Labels
            Down = downByMonth.Select(s => s.MGType).ToList();
        }
    }
    }

VC3EYE/Pages/EditService.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using System.Security.Claims;

using VC3EYE.Data;
using VC3EYE.Entities;
using VC3EYE.Models;

namespace VC3EYE.Pages
{
    [Authorize(Roles = SiteRoles.Administrator + "," + SiteRoles.User)]
    public class EditServiceModel : PageModel
    {
        private readonly Vc3eyeContext _db;

        public EditServiceModel(Vc3eyeContext db)
        {
            _db = db;
        }

        [BindProperty]
        public ServiceModel Service { get; set; }

        public void OnGet(int serviceid)
        {
            var sc = new ServiceController(_db);
            var service = sc.GetServiceByServiceID(serviceid);

            int minutes = Convert.ToInt32(service.CheckInterval.ToString().Split(':')[1]);

            var serviceM = new ServiceModel()
            {
                ServiceID = service.ServiceId,
                ServiceName = service.ServiceName,
                ServiceURL = service.Url,
                Location = service.Location,
                IPAddress = service.Ipaddress,
                GeneralInformation = service.GeneralInformation,
                IsImportant = service.IsImportant,
                IsActive = service.IsActive,
                Port = service.Port,
                RSSFeedLink = service.RssfeedLink,
                CheckInterval = minutes.ToString(),
                NumOfBackup = service.NumOfBackup,
                IsRunning = service.IsRunning,
                IsInternal = service.IsInternal,
                NotificationMessage = service.NotificationMessage,
                IsDeleted = service.IsDeleted,
                NotifyByMSTeams = service.NotifyByMsteams,
                LookupTerm = service.LookupTerm
            };

            Service = serviceM;
        }

        public IActionResult OnPostEdit(int serviceid)
        {
            if (ModelState.IsValid)
            {
                Service.ServiceID = serviceid;
                var sc = new ServiceController(_db);
                bool updated = sc.ModifyService(Service);

                if (updated)
                {
                    var lm = new LogsManager(_db);
                    var userLog = new Log()
                    {
                        LogName = "Update",
                        LogDescription = "Service - " + Service.ServiceName,
                        IsAudit = false,
                        DateAdded = DateTime.Now,
                        UserId = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier).ToString())
                    };

                    lm.AddUserActivityLog(userLog);

                    return RedirectToPage("EditService", new { @serviceid = serviceid, @m = "updated" });
                }
                else
                {
                    return RedirectToPage("EditService", new { @serviceid = serviceid, @m = "upfailed" });
                }
            }

            return Page();
        }
    }
}

VC3EYE/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace VC3EYE.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

VC3EYE/Pages/ErrorLogs.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using VC3EYE.Data;
using VC3EYE.Entities;

namespace VC3EYE.Pages
{
    [Authorize(Roles = SiteRoles.Administrator)]
    public class ErrorLogsModel : PageModel
    {
        private readonly Vc3eyeContext _db;

        public ErrorLogsModel(Vc3eyeContext db)
        {
            _db = db;
        }

        public List<ErrorLog> ErrorLogs { get; set; }
        public int TotalErrorLogs { get; set; }

        public void OnGet()
        {
            var lc = new LogsController(_db);
            TotalErrorLogs = lc.GetAllErrorLogs().Count;
            ErrorLogs = lc.GetAllErrorLogs();
        }
    }
}

VC3EYE/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using VC3EYE.Data;
using VC3EYE.Entities;

namespace VC3EYE.Pages
{
    [Authorize]
    public class IndexModel : PageModel
    {
        public List<Service> services { get; set; }

        private readonly ILogger<IndexModel> _logger;
        private readonly Vc3eyeContext _db;

        [BindProperty]
        [Required(ErrorMessage = "Please enter a search term.")]
        public string search { get; set; }
        public bool IsFiltered { get; set; }
        public List<string> Locations { get; set; }

        public IndexModel(ILogger<IndexModel> logger, Vc3eyeContext db)
        {
            _logger = logger;
            _db = db;
        }

        public void OnGet(string location)
        {
            var serv = new ServiceController(_db);
            Locations = serv.GetLocations();

            if (string.IsNullOrEmpty(location))
            {
                services = serv.GetCurrentServices().OrderBy(service => service.IsRunning).ThenBy(service => !service.IsImportant).ToList();
            }
            else
            {
                services = serv.GetServiceLocation(location).OrderBy(service => service.IsRunning).ThenBy(service => !service.IsImportant).ToList();
            }
        }

        public IActionResult OnPostSearch()
        {
            var sc = new ServiceController(_db);
            Locations = sc.GetLocations();

            if (!ModelState.IsValid)
            {
                services = sc.GetCurrentServices().OrderBy(service => service.IsRunning).ThenBy(service => !service.IsImportant).ToList(); 
                search = "";
                return Page();
            }
           

            services = sc.GetServiceBySearch(search).OrderBy(service => service.IsRunning).ThenBy(service => !service.IsImportant).ToList();

            IsFiltered = true;

            search = "";

            return Page();
        }

        
    }
}

VC3EYE/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using VC3EYE.Data;
using VC3EYE.Models;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace VC3EYE.Pages
{
    public class LoginModel : PageModel
    {
        private readonly Vc3eyeContext _db;
        public LoginModel(Vc3eyeContext db)
        {
            _db = db;
        }

        [BindProperty]
        public LoginInfoModel Login { get; set; }

        
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = new LoginManager(_db).GetUserLoggedIn(Login);

                string userEmail = "";
                string userName = "";
                string userRole = "";
                string userID = "";

                if (user != null)
                {
                    userEmail = user.Email ?? "";
                    userName = user.FirstName + " " + user.LastName;
                    userRole = user.Role.Description.ToLower();
                    userID = user.UserId.ToString();

                    if (!string.IsNullOrEmpty(userEmail) && !string.IsNullOrEmpty(userName))
                    {
                        var claims = new List<Claim> {
                        new Claim(ClaimTypes.Email, userEmail),
                        new Claim(ClaimTypes.Name, userName),
                        new Claim(ClaimTypes.NameIdentifier, userID)
                    };

                        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                        claimsIdentity.AddClaim(new Claim(ClaimTypes.Role, userRole));
                        AuthenticationProperties authProperties = new AuthenticationProperties
                        {
                            IsPersistent = true
                        };

                        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                               new ClaimsPrincipal(claimsIdentity), authProperties);
                    }                 
                }
                else
                {
                    ModelState.AddModelError("Login.LoginError", "Incorrect Email or Password");
                }
            }

            return Page();
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await HttpContext.SignOutAsync();
          
            return RedirectToPage("/Index");
        }
    }
}

VC3EYE/Pages/Logs.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VC3EYE.Data;
using VC3EYE.Entities;

namespace VC3EYE.Pages
{
    [Authorize(Roles = SiteRoles.Administrator + "," + SiteRoles.User)]
    public class LogsModel : PageModel
    {
        private readonly Vc3eyeContext _db;

        public LogsModel(Vc3eyeContext db)
        {
            _db = db;
        }

        public List<Log> SiteLogs { get; set; }
        public int NumOfPages { get; set; }
        public int TotalLogs { get; set; }

        public void OnGet(int p)
        {
            var lc = new LogsController(_db);

            int perPage = 15;
            int totalLogs = lc.GetAllLogs().Count;
            TotalLogs = totalLogs;
            int numOfPages = (int)Math.Ceiling((double)totalLogs / perPage);

            NumOfPages = numOfPages;

            SiteLogs = lc.GetAllLogs().OrderByDescending(x => x.DateAdded).Skip((p - 1) * perPage).Take(perPage).ToList();          
        }
    }
}

VC3EYE/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VC3EYE.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

VC3EYE/Pages/Settings.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VC3EYE.Data;
using VC3EYE.Models;
using VC3EYE.Entities;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace VC3EYE.Pages
{
    [Authorize(Roles = SiteRoles.Administrator)]
    public class SettingsModel : PageModel
    {
        private readonly Vc3eyeContext _db;
        public string Message { get; set; }

        [BindProperty]
        public Setting Setting { get; set; }
        public SettingsModel(Vc3eyeContext db)
        {
            _db = db;
        }
        public void OnGet()
        {
            var sc = new SettingContoller(_db);

            Setting = sc.GetCurrentSetting();
        }
        public async Task<IActionResult> OnPostSave(int settingid)
        {
            if(settingid > 0)
            {
                var sm = new SettingManager(_db);
                var sc = new SettingContoller(_db);
                var s = sm.GetSettingByID(settingid);

                if(s != null)
                {
                    s.SmtpPort = Setting.SmtpPort;
                    s.SmtpPassword = Setting.SmtpPassword;
                    s.MtClientId = Setting.MtClientId;
                    s.MtSecretKey = Setting.MtSecretKey;

                    sc.UpdateSetting(s);
                }
            }
            else
            {
                if (ModelState.IsValid)
                {
                    await _db.Settings.AddAsync(Setting);
                    await _db.SaveChangesAsync();
                    Message = "Successfully Added Settings";
                    //return RedirectToPage("Services");
                }
            }
            

            return Page();
        }
    }
}

VC3EYE/Pages/ViewUsers.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VC3EYE.Data;
using VC3EYE.Models;
using VC3EYE.Entities;
using Microsoft.EntityFrameworkCore;

namespace VC3EYE.Pages
{
    public class ViewUsersModel : PageModel
    {
        private readonly Vc3eyeContext _db;
        public List<User> user { get; set; }
        public ViewUsersModel(Vc3eyeContext db)
        {
            _db = db;
        }


        //public List<User> GetAllUsers()
        //{
        //    List<User> UserS= _db.Users.Include(x => x.Role).ToList();

        //    return UserS;
        //}
        public void OnGet()
        {
            
            user=_db.Users.Include(x => x.Role).ToList();

        }
    }
}

VC3EYE/Pages/AddService.cshtml
@page
@model VC3EYE.Pages.AddServiceModel
@{
    ViewData["Title"] = "Add Service";
}

@*JavaScript pop-up*@
<input type="hidden" id="message" value="@Model.Message" />

<script>
    function showMessage() {
        var message = document.getElementById("message").value;
        alert(message);
    }

//document.getElementById("btnAdd").addEventListener("click", showMessage);
</script>

<div class="border-1 container-fluid mt-4">
    <h1>Add Service</h1>

    <hr />

    <form method="post">
        <div class="form-container">
            <div class="row">
                <div class="col-sm-6 mb-3">
                    <label asp-for="currentService.ServiceName"><b>Service Name</b></label>
                    <input type="text" asp-for="currentService.ServiceName" class="form-control" />
                    <span asp-validation-for="currentService.ServiceName" class="text-danger"></span>
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="currentService.ServiceURL"><b>Service URL</b></label>
                    <input type="text" asp-for="currentService.ServiceURL" class="form-control" />
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="currentService.Location"><b>Location</b></label>
                    <input type="text" asp-for="currentService.Location" class="form-control" />
                    <span asp-validation-for="currentService.Location" class="text-danger"></span>
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="currentService.IPAddress"><b>IP Address</b></label>
                    <input type="text" asp-for="currentService.IPAddress" class="form-control" />
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="currentService.GeneralInformation"><b>General Information</b></label>
                    <input type="text" asp-for="currentService.GeneralInformation" class="form-control" />
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="currentService.Port"><b>Port</b></label>
                    <input type="number" asp-for="currentService.Port" class="form-control" />
                    <span asp-validation-for="currentService.Port" class="text-danger"></span>
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="currentService.RSSFeedLink"><b>RSS Feed Link</b></label>
                    <input type="text" asp-for="currentService.RSSFeedLink" class="form-control" />
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="currentService.LookupTerm"><b>Lookup Term</b></label>
                    <input type="text" asp-for="currentService.LookupTerm" class="form-control" />
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="currentService.CheckInterval"><b>Check Interval (mins)</b></label>
                    <input type="text" asp-for="currentService.CheckInterval" class="form-control" />
                    <span asp-validation-for="currentService.CheckInterval" class="text-danger"></span>
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="currentService.NumOfBackup"><b>Number of Backup(s)</b></label>
                    <input type="number" asp-for="currentService.NumOfBackup" class="form-control" />
                </div>
                <div class="col-sm-6 form-check mt-4">
                    <div class="service-important-chkbox">
                        <input type="checkbox" class="form-check-input" asp-for="currentService.IsImportant" />
                        <label class="form-check-label" asp-for="currentService.IsImportant">
                            Important
                        </label>
                    </div>
                </div>
            </div>
            <button type="submit" id="btnBack" value="GoBack" asp-page-handler="GoBack" class="btn btn-primary mb-3 ml-3">Go Back <i class="bi bi-backspace-fill"></i></button>

            <button type="submit" id="btnAdd" value="Add" asp-page-handler="Add" class="btn btn-success mb-3 ml-3">Add <i class="bi bi-plus-circle"></i></button>
        </div>
    </form>
</div>

@Html.Raw(ViewData["Script"])

VC3EYE/Pages/Chartsofservices.cshtml
@page
@model VC3EYE.Pages.ChartsofservicesModel
@{
    ViewData["Tittle"] = "Service Down History";

}
<canvas id="salesChart" width="400" height="200"></canvas>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.5.0/dist/chart.min.js"></script>
    <script>
        var salesData = {
            labels: @Json.Serialize(Model.Months),
            datasets: [{
                label: 'ServiceDown',
                data: @Json.Serialize(Model.Down ),
                borderColor: 'rgb(255, 99, 132)',
                tension: 0.1
            }]
        };
        var chartOptions = {
            responsive: true,
            maintainAspectRatio: false,
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        };

        var salesChart = new Chart(document.getElementById('salesChart').getContext('2d'), {
            type: 'line',
            data: salesData,
            options: chartOptions
        });
    </script>
}

VC3EYE/Pages/EditService.cshtml
@page
@model VC3EYE.Pages.EditServiceModel
@{
    int serviceID = Model.Service.ServiceID;

    //string disabled = (!Model.Service.IsActive && Model.Service.IsDeleted) ? "disabled" : "none";

    ViewData["Title"] = "Edit Service";
}

<div class="container-fluid mt-3">
    <h1>Edit @Model.Service.ServiceName</h1>
    <hr />
    <partial name="_Message" />
    @if (!Model.Service.IsDeleted)
    {
        <form method="post" asp-page-handler="Edit" asp-route-serviceid="@serviceID">
            <div class="row">
                <div class="col-sm-6 mb-3">
                    <label asp-for="Service.ServiceName"><b>Service Name</b></label>
                    <input type="text" asp-for="Service.ServiceName" class="form-control" />
                    <span asp-validation-for="Service.ServiceName" class="text-danger"></span>
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="Service.ServiceURL"><b>Service URL</b></label>
                    <input type="text" asp-for="Service.ServiceURL" class="form-control" />
                    <span asp-validation-for="Service.ServiceURL" class="text-danger"></span>
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="Service.Location"><b>Location</b></label>
                    <input type="text" asp-for="Service.Location" class="form-control" />
                    <span asp-validation-for="Service.Location" class="text-danger"></span>
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="Service.IPAddress"><b>IP Address</b></label>
                    <input type="text" asp-for="Service.IPAddress" class="form-control" />
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="Service.GeneralInformation"><b>Description</b></label>
                    <div class="form-floating">
                        <textarea class="form-control" placeholder="Leave a comment here" asp-for="Service.GeneralInformation" style="height: 100px"></textarea>
                    </div>
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="Service.Port"><b>Port</b></label>
                    <input type="number" asp-for="Service.Port" class="form-control" />
                    <span asp-validation-for="Service.Port" class="text-danger"></span>
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="Service.RSSFeedLink"><b>RSS Feed Link</b></label>
                    <input type="text" asp-for="Service.RSSFeedLink" class="form-control" />
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="Service.LookupTerm"><b>Lookup Term</b></label>
                    <input type="text" asp-for="Service.LookupTerm" class="form-control" />
                    <span asp-validation-for="Service.LookupTerm" class="text-danger"></span>
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="Service.CheckInterval"><b>Check Interval (mins)</b></label>
                    <input type="text" asp-for="Service.CheckInterval" class="form-control" />
                    <span asp-validation-for="Service.CheckInterval" class="text-danger"></span>
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="Service.NumOfBackup"><b>Number of Backup(s)</b></label>
                    <input type="number" asp-for="Service.NumOfBackup" class="form-control" />
                </div>
                <div class="col-sm-6 form-check mt-4">
                    <div class="row">
                        <div class="col-2">
                            <div class="service-important-chkbox">
                                <input type="checkbox" class="form-check-input" asp-for="Service.IsImportant" />
                                <label class="form-check-label" asp-for="Service.IsImportant">
                                    Important
                                </label>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="service-important-chkbox">
                                <input type="checkbox" class="form-check-input" asp-for="Service.IsInternal" />
                                <label class="form-check-label" asp-for="Service.IsInternal">
                                    Internal
                                </label>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="service-important-chkbox">
                                <input type="checkbox" class="form-check-input" asp-for="Service.NotifyByMSTeams" />
                                <label class="form-check-label" asp-for="Service.NotifyByMSTeams">
                                    Notify By MS Teams
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 mb-3">
                    <label asp-for="Service.NotificationMessage"><b>Notification Message</b></label>
                    <div class="form-floating">
                        <textarea class="form-control" placeholder="Leave a comment here" asp-for="Service.NotificationMessage" style="height: 100px"></textarea>
                    </div>
                </div>
            </div>
            <a asp-page="/ServiceInfo" asp-route-serviceid="@serviceID" class="btn btn-primary m-1"> Go Back <i class="bi bi-backspace-fill"></i></a>
            <button type="submit" class="btn btn-success">Update <i class="bi bi-pencil-square"></i></button>
        </form>
    }
    else
    {
        <div class="alert alert-warning" role="alert">
            <i class="bi bi-exclamation-triangle"></i> Cannot edit deleted service!
        </div>
    }
</div>

VC3EYE/Pages/Settings.cshtml
@page
@model VC3EYE.Pages.SettingsModel
@{
    ViewData["Title"] = "Settings";

    int settingid = (Model.Setting != null) ? @Model.Setting.SettingId : 0;
}

<form method="post" asp-page-handler="Save" asp-route-settingid="@settingid">
    <div class=" mt-3 ">
        <h1>Settings</h1>
    </div>
    <hr />
    <div class="border p-3 mt-4">
        <div asp-validation-summary="All"></div>
        

        <div class="mb-3">
            <label asp-for="Setting.SmtpPort"></label>
            <input asp-for="@Model.Setting.SmtpPort" class="form-control">
        </div>
        <div class="mb-3">
            <label asp-for="Setting.SmtpUserName"></label>
            <input asp-for="@Model.Setting.SmtpUserName" class="form-control">
        </div>
        <div class="mb-3">
            <label asp-for="Setting.SmtpPassword"></label>
            <input type="password" asp-for="@Model.Setting.SmtpPassword" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Setting.MtClientId"></label>
            <input asp-for="@Model.Setting.MtClientId" class="form-control" />
            <span asp-validation-for="Setting.MtClientId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Setting.MtSecretKey"></label>
            <input asp-for="@Model.Setting.MtSecretKey" class="form-control" />
        </div>          
        <div>
            <button type="submit" class="btn btn-primary" style="width:150px;">Save</button>
        </div>
    </div>
    </form>
@Model.Message